### ISSUE TITLE
Convert address to base58?

### ISSUE THREAD

**Issue by alexiskattan** [Anderson-Juhasc/dogecoin-bip84#1]
Loving just playing around with this library.  Thank you.  Was just coding up a little test thing.  I copied and pasted a sample of the code.  The issue is the result when using testnet gives an address `td1qjdk4ashlydvrne997tls6cn7g9tpkq29q2fq6n`.  However when I try and put this into my wallet, it gives an error about it not being base58.   How do we go between what is outputted by `account0.getAddress(0)` and what can be used in a wallet?

```
const { fromMnemonic, fromZPrv, fromZPub } = require('dogecoin-bip84')

var mnemonic = 'dolphin depart wild cannon fitness tennis emotion fruit tired dress office about pupil level iron'
var root = new fromMnemonic(mnemonic, '', true)
var child0 = root.deriveAccount(0)
var account0 = new fromZPrv(child0)
console.log('Address:', account0.getAddress(0))
```

I copied and pasted the `td1qjdk4ashlydvrne997tls6cn7g9tpkq29q2fq6n` into a base58 converter, but it didn't work either.

**Comment by Anderson-Juhasc** [comment]
@alexiskattan Which wallet are you using? Core? It must be because no supported in any wallet yet.

**Comment by alexiskattan** [comment]
Yes.  I was using Dogecoin Core (with testnet).  I also just tried to do a transaction with `bitcore-lib-doge` and it gave the error `UnhandledPromiseRejectionWarning: Error: Non-base58 character`.  Would love to use Bech32 but I don't know how to get it into the system.  Have you had any luck doing a transaction with one of these addresses?

**Comment by Anderson-Juhasc** [comment]
@alexiskattan no, I created the library providing for the need to update the other wallets.

**Comment by Anderson-Juhasc** [comment]
@alexiskattan but with this library you can use the bip44 and bip49 for while until they update the wallets for work with bip84, the private key is the same.
